clients:
    'Signature Analytics':
        authenticationProvider: google
        workspace: 0000-1234-1234-0000
        roles: [exec, hr, sales, employee]
        dashboards:
            'company-overview':
                id: 1234-0000-1234-0002
                allowedRoles: [employee]
            'human-resources-overview': 
                id: 1234-0000-1234-0000
                allowedRoles: [employee, exec, hr]
            'sales-overview': 
                id: 1234-0000-1234-0001
                allowedRoles: [employee, exec, hr]

        users:
            'pheald@signatureanalytics.com': 
                roles: [employee, hr, sales]

            jason
            izett
            david
            chris
            ray            

    magna_trucking: 