name: Azure Static Web Apps CI/CD

on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened, closed]
        branches:
            - main

jobs:
    build_and_deploy_job:
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
        runs-on: ubuntu-latest
        name: Build and Deploy Job
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: true
            - name: Set up Node.js version
              uses: actions/setup-node@v1
              with:
                  node-version: '14.x'
            - name: Test
              env: 
                WEBAPP_CLIENT_ID: ${{ secrets.WEBAPP_CLIENT_ID }}
                WEBAPP_CLIENT_SECRET: ${{ secrets.WEBAPP_CLIENT_SECRET }}
                WORKSPACE_AUTOMATEDTESTING: ${{ secrets.WORKSPACE_AUTOMATEDTESTING }}
              run: |
                set -ev
                echo "`dig @8.8.8.8 +short +time=30 app.powerbi.com | tail -n1` app.powerbi.com" | sudo tee -a /etc/hosts

                cd api
                npm ci
                cd ..

                cd ui
                npm ci
                npm run build
                npx playwright install
                npm test -- --workers=1 --retries=2
                cd ..
            - name: Upload screenshots
              if: ${{ failure() }}
              uses: actions/upload-artifact@v1
              with:
                  name: screenshots
                  path: ./ui/test-results

            - name: Build And Deploy
              id: builddeploy
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_ROCK_08D91C91E }}
                  repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
                  action: 'upload'
                  ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
                  # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
                  app_location: 'ui' # App source code path
                  api_location: 'api' # Api source code path - optional
                  output_location: 'build' # Built app content directory - optional
                  app_build_command: 'ls -al build'
                  ###### End of Repository/Build Configurations ######

    close_pull_request_job:
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        runs-on: ubuntu-latest
        name: Close Pull Request Job
        steps:
            - name: Close Pull Request
              id: closepullrequest
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_ROCK_08D91C91E }}
                  action: 'close'
